name: Zipline CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.5]
  steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.1.1
      with:
        python-version: ${{ matrix.python-version }}
    # TODO: set up pip cache
    - name: Install requirements
      run: |
        python -m pip install -r etc/requirements_build.in -c etc/requirements_locked.txt
        python -m pip install --no-binary=bcolz -e .[all] -r etc/requirements_blaze.in -c etc/requirements_locked.txt
    - name: Run tests
      run: |
        nosetests tests
