name: Zipline CI (Windows)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.6]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    # - name: pip cache
    #   uses: actions/cache@v2
    #   with:
    #     path: ${{ steps.pip-cache.outputs.dir }}
    #     key: ${{ runner.os }}-pip-${{ hashFiles('etc/requirements_py36_locked.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
    # - name: Install requirements
    #   run: |
    #     python -m pip install -r etc/requirements_build.in -c etc/requirements_locked.txt
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install scientific python requirements
      run: |
        conda install -y -vv pandas==0.22.0 numpy==1.19.1 scipy==1.5.0 cython==0.29.21
    - name: Install TA lib
      run: |
        (New-Object Net.WebClient).DownloadFile('http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-msvc.zip', 'ta-lib-0.4.0-msvc.zip')
        Add-Type -AssemblyName System.IO.Compression.FileSystem;[System.IO.Compression.ZipFile]::ExtractToDirectory('ta-lib-0.4.0-msvc.zip', 'C:\')
        cd C:\ta-lib\c\make\cdr\win32\msvc
        nmake
        conda install -c quantopian -vv ta-lib
    - name: Install other requirements
      run: |
        pip install --no-binary=bcolz -e .[all] -c etc/requirements_py36_locked.txt

    - name: Run tests
      run: |
        nosetests tests
